version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@headlessui/react"
    versions:
    - 0.3.2
    - 1.0.0
    - 1.1.0
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: next
    versions:
    - 10.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: msw
    versions:
    - 0.28.1
