backend:
  name: git-gateway
  branch: trunk
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
site_url: https://web.site
collections:
  - name: blog
    label: Blog Post
    folder: "src/collections/blog"
    extension: md
    create: true
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Date Published", name: "date_published", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
